version: "3.8"

services:
  database:
    container_name: docker-mysql-database
    platform: linux/arm64/v8
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3307:3308
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - mysql_db_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - docker-mysql-network

  phpmyadmin:
    container_name: docker-mysql-phpmyadmin
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8089:80
    env_file: .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - docker-mysql-network

  # postgresql:
  #   container_name: docker-postgresql
  #   platform: linux/arm64/v8
  #   image: 'bitnami/postgresql:latest'
  #   restart: unless-stopped
  #   ports:
  #     - 54321:5432
  #   volumes:
  #     - postgresql_db_data:/bitnami/postgresql
  #   environment:
  #     - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
  #     - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
  #     - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
  #     - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}

  # mongodb:
  #   container_name: docker-mongodb
  #   platform: linux/arm64/v8
  #   image: mongo:latest
  #   restart: unless-stopped
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb_db_data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #   networks:
  #     - docker-mysql-network

  # mongodb-express:
  #   container_name: docker-mongodb-express
  #   depends_on:
  #     - mongodb
  #   image: mongo-express:latest
  #   restart: unless-stopped
  #   ports:
  #     - 8087:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
  #   networks:
  #     - docker-mysql-network

volumes:
  mysql_db_data:
    driver: local
  postgresql_db_data:
    driver: local
  mongodb_db_data:
    driver: local

networks:
  docker-mysql-network:
    driver: bridge  